version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile-web
        restart: always
        hostname: web
        ports:
          - 8011:8011
networks:
  default:
    external:
      name: my-net
