server:
    port: 8011
#    ssl:
#      key-store: classpath:keystore.p12
#      key-store-password: xjp32.
#      key-store-type: PKCS12
#      key-alias: tomcat
spring:
    application:
        name: web
    thymeleaf:
    #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        #开发过程中需将缓存关闭
        cache: false
        check-template: false