spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root123
        url: jdbc:mysql://192.168.0.25:3306/tj-hwzj?serverTimezone=GMT
        sql-script-encoding: UTF-8
        platform: mysql
    redis:
        #Redis数据库索引（默认为0）
        database: 0
        host: localhost
        port: 6379
        password: libin19830213
        #连接超时时间（毫秒）
        timeout: 5
        pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            #连接池中最大空闲连接
            max-idle: 8
            #连接池中最小空闲连接
            min-idle: 1
file:
    server: /data/0/hyzy/
    #ffmpeg读取视频的工具绝对路径
    ffmpeg: /Project/tdd/frontend/media/tool/ffmpeg.exe