server:
    port: 8015
    context-path: /media
spring:
    profiles:
        active: dev
    application:
        name: media
    thymeleaf:
    #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        #开发过程中需将缓存关闭
        cache: false
        check-template: false
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        multipart:
            max-file-size: 100Mb
            max-request-size: 100Mb
#mybatis-plus配置
mybatis-plus:
    mapper-locations: classpath:/com/frontend/media/mapper/xml/*Mapper.xml
    #实体扫描
    type-aliases-package: com.frontend.media.entity
    global-config:
        #主键类型 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID
        id-type: 3
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
        #全局表前缀
#        table-prefix: cms
        #刷新mapper 调试神器
        refresh-mapper: true
        #数据库大写下划线转换
        capital-mode: true
        # Sequence序列接口实现类配置
        key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
        #逻辑删除配置（下面3个配置）
        logic-delete-value: 1
        logic-not-delete-value: 0
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        #自定义填充策略接口实现
        meta-object-handler: com.frontend.media.handler.MyMetaObjectHandler
    configuration:
        #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
        map-underscore-to-camel-case: true
        cache-enabled: false
        #配置JdbcTypeForNull, oracle数据库必须配置
        jdbc-type-for-null: 'null'