spring:
  application:
    name: eureka-server
---
spring:
    profiles: peer1
server:
  port: 1025
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #是否将自己注册到Eureka，默认为true
#    register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true
#    fetch-registry: false
    service-url:
      #与Eureka Server交互地址，多个用，分隔
      defaultZone: http://eureka2:1026/eureka/
    #健康检查
    healthcheck:
      enabled: true
  server:
    #关闭自我保护
    enable-self-preservation: false
---
spring:
    profiles: peer2
server:
  port: 1026
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #是否将自己注册到Eureka，默认为true
#    register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true
#    fetch-registry: false
    service-url:
      #与Eureka Server交互地址，多个用，分隔
      defaultZone: http://eureka1:1025/eureka/
    #健康检查
    healthcheck:
      enabled: true
  server:
    #关闭自我保护
    enable-self-preservation: false

