spring:
  application:
    name: eureka-server
server:
  port: 1025
eureka:
  instance:
    hostname: http://localhost
    prefer-ip-address: true
  client:
    #是否将自己注册到Eureka，默认为true
    register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      #与Eureka Server交互地址，多个用，分隔
      defaultZone: http://localhost:1025/eureka/
    #健康检查
    healthcheck:
      enabled: true
  server:
    #关闭自我保护
    enable-self-preservation: false