FROM java:alpine

VOLUME /tmp/media

ADD /jar/media-1.0-SNAPSHOT.jar /app.jar

RUN apk update
RUN apk add yasm && apk add ffmpeg

#RUN bash -c 'touch /app.jar'

#更改时区
RUN apk add -U tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 8015

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]