FROM java:8

VOLUME /tmp/cms

ADD /jar/cms-1.0-SNAPSHOT.jar /app.jar

RUN bash -c 'touch /app.jar'

RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

EXPOSE 8301

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
