version: '3'
services:
    hwzy-media:
        build:
            context: ./
            dockerfile: Dockerfile-cms
        restart: always
        hostname: cms
        ports:
          - 8301:8301
        volumes:
          - /data/0/hyzy:/data/0/hyzy
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
networks:
  default:
    external:
      name: my-net
