FROM java:8

VOLUME /tmp/goods

ADD /target/service-goods-1.0.0.jar app.jar

RUN bash -c 'touch /app.jar'

EXPOSE 1025

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]

