server:
    port: 1002
eureka:
    client:
        service-url:
            defaultZone: http://localhost:1025/eureka/
    instance:
          prefer-ip-address: true
          hostname: localhost
spring:
    application:
        name: gateway
    redis:
        #Redis数据库索引（默认为0）
        database: 0
        host: 192.168.3.11
        port: 6379
        password: libin19830213
        #连接超时时间（毫秒）
        timeout: 5
        pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            #连接池中最大空闲连接
            max-idle: 8
            #连接池中最小空闲连接
            min-idle: 1
zuul:
    routes:
        oauth-server:
            path: /oauth/**
            serviceId: oauth-server
        service-user:
            path: /service-user/**
            serviceId: service-user
        service-goods:
            path: /service-goods/**
            serviceId: service-goods

filter:
    oauth:
        services: service-order, service-group-order

